const admin = require('firebase-admin');
const fs = require('fs');
const path = require('path');

// 1. Initialize Firebase Admin
// Path to your service account key file
const serviceAccountPath = path.join(process.cwd(), 'public', 'esim-f0e3e-firebase-adminsdk-fbsvc-2b085dbbcd.json');

if (!fs.existsSync(serviceAccountPath)) {
    console.error('Error: Service account file not found at:', serviceAccountPath);
    process.exit(1);
}

// Check if app is already initialized to avoid errors if running multiple times/contexts
if (admin.apps.length === 0) {
    const serviceAccount = require(serviceAccountPath);
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}

// 2. Function to fetch all users recursively
async function getAllUsers(nextPageToken) {
    // Fetch lists of users, 1000 at a time
    const listUsersResult = await admin.auth().listUsers(1000, nextPageToken);

    // Extract emails, filter out users without email
    let emails = listUsersResult.users
        .map(user => user.email)
        .filter(email => !!email);

    if (listUsersResult.pageToken) {
        // If there are more users, fetch next page
        const nextBatch = await getAllUsers(listUsersResult.pageToken);
        emails = emails.concat(nextBatch);
    }

    return emails;
}

// 3. Main execution
async function main() {
    try {
        console.log('Starting fetch of Firebase users...');

        const emails = await getAllUsers();
        console.log(`Successfully fetched ${emails.length} users with emails.`);

        if (emails.length === 0) {
            console.log('No emails found. No SQL generated.');
            process.exit(0);
        }

        // 4. Generate SQL
        // Escape single quotes in emails if necessary (rare, but good practice)
        const values = emails
            .map(email => `('${email.replace(/'/g, "''")}')`)
            .join(',\n  ');

        const sqlContent = `
/* 
   Generated SQL for importing Firebase users into Supabase 'newsletter' table.
   Date: ${new Date().toISOString()}
   Total Count: ${emails.length}
*/

-- Optional: Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS newsletter (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Users
INSERT INTO newsletter (email)
VALUES 
  ${values}
ON CONFLICT (email) DO NOTHING;
`;

        // 5. Write to file
        const outputPath = path.join(process.cwd(), 'newsletter_users.sql');
        fs.writeFileSync(outputPath, sqlContent);

        console.log(`\n✅ SQL file generated at: ${outputPath}`);
        console.log('You can now copy the content of this file and run it in the Supabase SQL Editor.');

    } catch (error) {
        console.error('❌ Error generating SQL:', error);
        process.exit(1);
    } finally {
        // Force exit to ensure script doesn't hang
        process.exit(0);
    }
}

main();
